### ISSUE TITLE
SRT not working when high latency between server and client

### ISSUE THREAD

**Issue by jahaddow** [bluenviron/mediamtx#3756]
I have mediamtx running on a VPS in London, UK and I am in Australia. When sending via SRT the log shows constant connects and disconnects. I have tried multiple VPS in London and the same problem occurs. It does not happen to my servers in Australia and USA.

Everything is pointing towards an issue when the latency between client and server is high, in this case, over 250ms. The same issue also occurs when trying to read a stream via SRT.

Looking at it further, mediamtx seems to show the source connecting multiple times which appears to be breaking it. The same occurs for clients reading. If I set mediamtx to disallow publish override then publish starts working, but read still does not.

2024/09/10 13:45:58 INF [SRT] [conn 159.196.xxx.xxx:48962] opened
2024/09/10 13:45:59 INF [SRT] [conn 159.196.xxx.xxx:48962] opened
2024/09/10 13:45:59 INF [path zowie2] closing existing publisher
2024/09/10 13:45:59 INF [SRT] [conn 159.196.xxx.xxx:48962] closed: terminated
2024/09/10 13:45:59 INF [SRT] [conn 159.196.xxx.xxx:48962] opened
2024/09/10 13:45:59 INF [path zowie2] closing existing publisher
2024/09/10 13:45:59 INF [SRT] [conn 159.196.xxx.xxx:48962] closed: terminated
2024/09/10 13:46:01 INF [SRT] [conn 159.196.xxx.xxx:48962] closed: astits: no more packets

## Which version are you using?

v0.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by jahaddow** [comment]
If I leave the source (OBS or Encoder) to try and constantly connect, eventually after a few mins they will be successful and maintain connection until stopped. I can't seem to make it work for reading clients however.

**Comment by jahaddow** [comment]
I have been doing some testing using various VPN servers around the world to try and test at what latency SRT fails to connect. It seems to be somewhere between 200-250ms. Anything with a static latency over that then SRT just completely refuses to work on Mediamtx.

**Comment by Frenzie** [comment]
Some further testing shows the problem doesn't occur with the sample server over at `gosrt`: https://github.com/datarhei/gosrt/blob/f2ff8a3cc35debc3f7080d6f0a94a93cac609940/contrib/server/main.go#L192

It shows something somewhat similar in the logs when the delay is somewhere above 200 ms, but it manages to get past it.

```
PUBLISH         START /myapp/stream1 (172.17.0.2:36117) publishing
CONNECT      CONFLICT /myapp/stream1 (172.17.0.2:36117) already publishing
CONNECT      CONFLICT /myapp/stream1 (172.17.0.2:36117) already publishing
CONNECT      CONFLICT /myapp/stream1 (172.17.0.2:36117) already publishing
```

That program works slightly differently. You need something like `server -addr :8890 -app /myapp` coupled with `ffmpeg -re -i /home/root/some-video.mp4 -c copy -f mpegts "srt://172.17.0.1:8890?streamid=publish:/myapp/stream1&latency=4000000"`, and then for example `srt://localhost:8890?streamid=/myapp/stream1` to view the result.

**Comment by lfleuter** [comment]
I am having a similar problem - when latency is too high, the publisher terminates and my streaming software (e.g. OBS Studio) hangs up and shows "Connecting" (instead of throwing an error message that it is not possible to publish the stream or showing "Stop stream"). If I try to embed the same stream into OBS Studio I also do not see it.

Sometimes something weird happens though. The mediaMTX logs no longer show that the publisher has been terminated, but at the same time there is no message that a publisher is available. In addition, according to the logs, the reader connection is closed because no one is publishing. However, when I try to embed the same stream into OBS Studio, I can see the stream even if the button in OBS Studio still shows "Connecting". So basically OBS Studio somehow does not seem to get any feedback from mediaMTX about a stream being published and at the same time I also do not see in the mediaMTX logs that a stream is being published.

**Comment by jahaddow** [comment]
Any devs able to comment on this issue? Doesn't seem to be an isolated issue and makes cross continent streaming near impossible via SRT.

**Comment by m06antwe** [comment]
I have the same issue. My latency on the connection between the MediaMTX instances is around 350ms. I'm using FFMPEG to forward SRT streams, but get the exact same error output as @Frenzie.

I'm trying to tweak the SRT timeout and other parameters, but can't get this to work... Anyone that has input? Would be highly appreciated. Thanks.

`ffmpeg -i srt://192.168.1.213:8890?streamid=read:STRID01 -c copy -fflags nobuffer -f mpegts srt://10.1.32.104:8890?streamid=publish:STRID01`

**Comment by mrk3767** [comment]
Jumping in on this one as well. I have this running on a pretty powerful machine in a datacenter with a fiber connection. I've had 5 or 6 clients publishing with no issue for hours at a time, but one of the clients who has latency that spikes every once in awhile gets disconnected every so often. The disconnect is typically just a hard cut that returns after about 2-3 seconds, goes out a second time and then comes back to normal after another 2-3 seconds. I have another SRT server running on a box next to this one that they can push into without any issues. There doesn't seem to be any quality loss on audio or video which makes me believe this is just a disconnect from MTX.

**Comment by Frenzie** [comment]
It might be worth retesting with #3992. I think I tested https://github.com/datarhei/gosrt/commit/f2ff8a3cc35debc3f7080d6f0a94a93cac609940 when I said the sample server at gosrt works fine, but I overlooked that's not the same as 0.7.0. The commits on 28 August sound like they may be relevant.

**Comment by aler9** [comment]
i merged #3992, let me know if it makes a difference.

**Comment by mrk3767** [comment]
@aler9 - I'm just jumping into this project and haven't compiled it on my own machine. I'm using the docker image to install onto a linux box. Any chance you or someone else can get the new build published to Docker? 

I can try to take a swing at building locally tomorrow morning if not. I see instructions for compiling, cross-compiling, and making all binaries. Will the command to make binaries with Docker also create a usable docker-ffmpeg image?

**Comment by Frenzie** [comment]
If you set this to false there's no problem:
https://github.com/bluenviron/mediamtx/blob/cf01683168b6fd525c1c3e68d05ef90f665dead8/mediamtx.yml#L477-L478
https://github.com/bluenviron/mediamtx/blob/cf01683168b6fd525c1c3e68d05ef90f665dead8/internal/core/path.go#L476-L479

Thinking aloud, and keep in mind I don't know Go, that suggests something along these lines should do the trick:
```diff
diff --git a/internal/core/path.go b/internal/core/path.go
index 4eeae3a4..7dbda1ec 100644
--- a/internal/core/path.go
+++ b/internal/core/path.go
@@ -83,6 +83,7 @@ type path struct {
        confMutex                      sync.RWMutex
        source                         defs.Source
        publisherQuery                 string
+       publisherAddedAt               time.Time
        stream                         *stream.Stream
        recorder                       *recorder.Recorder
        readyTime                      time.Time
@@ -473,6 +474,11 @@ func (pa *path) doAddPublisher(req defs.PathAddPublisherReq) {
        }
 
        if pa.source != nil {
+               if time.Since(pa.publisherAddedAt) < 2*time.Second {
+                       req.Res <- defs.PathAddPublisherRes{Err: fmt.Errorf("current publisher has been active for less than 2 seconds")}
+                       return
+               }
+
                if !pa.conf.OverridePublisher {
                        req.Res <- defs.PathAddPublisherRes{Err: fmt.Errorf("someone is already publishing to path '%s'", pa.name)}
                        return
@@ -485,6 +491,7 @@ func (pa *path) doAddPublisher(req defs.PathAddPublisherReq) {
 
        pa.source = req.Author
        pa.publisherQuery = req.AccessRequest.Query
+       pa.publisherAddedAt = time.Now()
 
        req.Res <- defs.PathAddPublisherRes{Path: pa}
 }
```

**Comment by lfleuter** [comment]
I already set "overridepublisher" to "no" and still face this issue. So at least for me this is not the solution.

**Comment by Frenzie** [comment]
You're right, it looks like the connection still fails if you up the latency to 2 seconds, but it remains successfully connected at 1.5. But in any case not closing the existing publisher quite so enthusiastically does a lot of good already.

**Comment by mrk3767** [comment]
Setting to false did help with one of the feeds, but I then found feeds with needs for longer latency settings and ran into the same problem again. I'm about to just fallback to RTMP... It seems like the SRT functionality here isn't working quite right just yet.

**Comment by philipthomasme** [comment]
Same here - unfortunately makes mediamtx unusable for our use case.
Any ETA for a fix, @aler9 ?

**Comment by secit** [comment]
I've encountered several stability issues with the current SRT implementation in pure Go. To address this, I've created a fork of this project that uses the official Haivision's Go bindings for their C++ library. This approach has proven significantly more stable during testing.

I successfully tested with **2000ms latency** without issues, both before connecting and during stream.
All previously encountered problems have been resolved in this fork.

Current Limitations:
 * ~~The srtReadPassphrase config is currently applied to both read and publish operations, causing srtPublishPassphrase to be ignored.~~
 * No statistics are implemented in this early-stage version.

@philipthomasme, could you test this fork to see if it resolves your specific issue? You can find the repository in my GitHub profile.
Please note that this is an **early-stage implementation**, and further refinements (e.g., statistics, passphrase handling, and tests) need to be addressed.

Important! You need to download and install Haivision's official SRT library for this fork do work.

Let me know if you need additional details or assistance!

**Comment by llamafilm** [comment]
I found this issue because I occasionally see the `astits: no more packets` error and also `EOF` in the logs.

Thanks @Frenzie for providing nice reproduction steps in Docker. I had to change it slightly since I'm on MacOS, so I run the ffmpeg sender in another container.  With version 1.14 my log looks slightly different:

```
2025/08/22 00:01:32 INF [SRT] listener opened on :8890 (UDP)
2025/08/22 00:01:34 INF [SRT] [conn 172.19.0.3:34815] opened
2025/08/22 00:01:35 INF [SRT] [conn 172.19.0.3:34815] opened
2025/08/22 00:01:37 INF [SRT] [conn 172.19.0.3:34815] closed: EOF
2025/08/22 00:01:39 INF [SRT] [conn 172.19.0.3:34815] closed: EOF
```

And the ffmpeg sender:
```
Output #0, mpegts, to 'srt://172.19.0.2:8890?streamid=publish:mystream1&latency=4000000&pkt_size=1316':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf60.16.100
  Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 12854 kb/s, 24 fps, 24 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2025-07-31T16:29:54.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[vost#0:0/copy @ 0xffffb358e330] Error submitting a packet to the muxer: I/O error
[out#0/mpegts @ 0xffffb4758e70] Error muxing a packet
[out#0/mpegts @ 0xffffb4758e70] Error writing trailer: I/O error
[out#0/mpegts @ 0xffffb4758e70] Error closing file: I/O error
[out#0/mpegts @ 0xffffb4758e70] video:3515kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.327388%
size=    3596kB time=00:00:02.79 bitrate=10553.5kbits/s speed=1.22x    
Conversion failed!
```

The timing issue seems the same; with 200ms delay it's fine, and with 300ms it fails.

**Comment by llamafilm** [comment]
@secit I'm not a go programmer but I'm wondering what is your opinion about haivision/srtgo vs datarhei/gosrt?  Could the latter be fixed or do you think it's best to switch to the Haivision one?

**Comment by philipthomasme** [comment]
@secit Thanks for your work.

We tested it but unfortunately we cannot really compare it to our current setup as we use authentication (and statistics) too. If we disable authentication, it generally works better as authentication seemingly introduces more "delay" which leads to an increase in the problems discussed here.

So if another person could test it, that would be great. We can get back to testing once authentication (and statistics) work but I understand that it is a lot of work, so I'm not sure if you plan on continuing to work on same.

**Comment by secit** [comment]
@philipthomasme Authentication and statistics was added a few months ago.
The statistics between the SRT libraries are not 1-to-1, so there are differences.

@llamafilm Both libraries are excellent choices. The SRT library was originally developed by Haivision, and their Go implementation directly interfaces with the official C++ library. As a result, it is likely to remain closely aligned and up to date with the latest developments in SRT technology.

In contrast, Datarhei’s version is a pure Go implementation that is essentially a translation of Haivision’s C++ library. While this approach eliminates the need for C++ bindings, it may introduce behavioral differences not present in the original C++ version—or, conversely, it may resolve issues that exist in the C++ code. Updates to this library may also be less frequent, especially if it is considered stable and functional.

That said, this isn’t the right place for an extended discussion regarding this. If you’d like to continue this conversation, please consider opening a ticket or starting a discussion thread in my forked repository. I’d be happy to chat over there!

**Comment by Xaver88** [comment]
Hi there
in mediamtx.yml I have
# SRT
srt: true
srtAddress: :8890

I also can see that [SRT] listener opened on :8890 (UDP)
Firewall also opend on 8890/udp
but the encoder (caller with 200ms) will not connect to mediamtx
what's going wrong
same Encoder can connect with RTMP to mediamtx and SRT to vMix

I see, that the encoder cannot send the streamID
I only can setup the IP, Port and latency

any solutions?

**Comment by wtomezaki** [comment]
same issue here. but only on the reader side, publisher works fine. Reader goes into a loop of connecting/disconnecting for a couple times then stabilizes and this only happens if I'm reading the stream over 200ms away.

**Comment by algora-pbc** [comment]
💎 **philipthomasme** is offering a **$10** bounty for this issue. View and reward the bounty at `algora.io/bluenviron/mediamtx/issues/3756`

👉 Got a pull request resolving this? Claim the bounty by commenting `/claim #3756` in your PR and joining `algora.io`

**Comment by aler9** [comment]
this is fixed by https://github.com/bluenviron/mediamtx/pull/5282 and also by upstream patch https://github.com/datarhei/gosrt/pull/123.

Thanks @Frenzie for providing instructions that allowed to precisely replicate the bug.

High latency causes SRT clients to send repeated handshake requests, but the server was not detecting them as duplicate of the first one, instead they were treated as brand new connections, causing the log mentioned above:

```
2025/08/22 00:01:34 INF [SRT] [conn 172.19.0.3:34815] opened
2025/08/22 00:01:35 INF [SRT] [conn 172.19.0.3:34815] opened
2025/08/22 00:01:37 INF [SRT] [conn 172.19.0.3:34815] closed: EOF
2025/08/22 00:01:39 INF [SRT] [conn 172.19.0.3:34815] closed: EOF
```

The patch fixes the issue by correctly detecting duplicate handshake requests.
